function axs = defaultAxes(varargin)
    uiP = IkUtils.visualization.Params;


     axs(r,c) = axes...
            (fig...
            ,tickdir = 'out'...
            , nextplot = 'add'...
            , Box = false...
            , fontName = uiP.Fontname...                            
            );

end