%% IK 29-5-24
function stats = histStatsMouseWrapperIK(mname, kwargs)
    arguments
        mname (1,1) string
        kwargs.event (1,1) string
        kwargs.modulating (1,1) logical
    end
    
            
    [curationResults, sessionsMask] = loadSimpleCurationResultSanitized(mname); 
    
    ephysData = loadAnalyzedEphysDataForMouse(mname);
    modulationRanges = IkUtils.getParams().sspkRanges;
    p = IkUtils.getParams();
    i = 1;
    stats = [];
    for s = 1:length(ephysData)
        sessionData = ephysData(s);
        for n = 1 : length(sessionData.neuron) 
            histStats = struct ...
                ( cs = computePsthStats ...
                ( sessionData.neuron(n).RasterXY_cs_filtered ...
                , modulationRanges.cs ...
                , p.psthRanges.cs_full ...
                ) ... 
                , us = computePsthStats ...
                ( sessionData.neuron(n).RasterXY_cs_filtered ... % IK change. Changed this to cs because we are only plotting the CS_aligned and the modulationranges for the us are also written as cs_aligned.
                , modulationRanges.us ...
                , p.psthRanges.cs_full ... 
                ) ...
                );
            histStats.cs.cs_facilitation = curationResults(s).modulation.cs_facilitation(n);
            histStats.cs.cs_suppression = curationResults(s).modulation.cs_suppression(n);
            histStats.us.us_facilitation = curationResults(s).modulation.us_facilitation(n);
            histStats.us.us_suppression = curationResults(s).modulation.us_suppression(n);
            stats.cs(i) = histStats.cs;
            stats.us(i) = histStats.us;
            i = i + 1;
        end
    end

    return

    sessionWrapper = @(eDat, curation) ...
        histStatsSessionWrapper ...
            ( eDat ...
            , curation ...
            , event = kwargs.event ...
            , modulating = kwargs.modulating ...
            , mname = mname ...
            );
    allIdcs.Shank2MUT = 1:2;
    allIdcs.Shank2WT = [];
    idcs = [allIdcs.Shank2MUT allIdcs.Shank2WT];
    stats = arrayfun ...
        ( sessionWrapper ...
        , ephysData(idcs) ...
        , curationResults(idcs) ...
        );
    
end
