% TODO: This function has thrown an error during curation, find the bug and/or
% wrap its calling in a try/catch block
function plotCrossCorrelation2 ...
                ( ax ...
                , complexChannelData, complexKsTrueId ...
                , simpleChannelData, simpleKsTrueId ...
                , mname ...
                , sessionIdx ...
                )
%%  Cross-correlation figure

    cla(ax)

    if isempty(simpleChannelData)
        warning("No simple channel for cross-correlation")

        title...
            ( ax ...
            , "No simple channel for cross-correlation" ...
            )
        return
    end
    
    spike_times_n_simple = simpleChannelData.st;
    spike_times_complex_spiking_neurons = complexChannelData.st;

    [ST_Offsets_n_simple, ~, ~] = crosscorrelogram ...
        ( spike_times_complex_spiking_neurons ...
        , spike_times_n_simple ...
        , getParams().cc_range ...
        );

    histogram...
        ( ax ...
        , ST_Offsets_n_simple...
        , 'BinWidth', getParams().cc_BinW...
        , 'BinLimits',getParams().cc_range...
        , 'Normalization','probability'...
        , 'EdgeColor','none'...
        , 'FaceColor',getColors().c_blue...
        );

    hold on

    title...
        ( ax ...
        , sprintf('Cross-correlation %s', mname) ...
        , sprintf ...
            ('S: %d, N: %d with N simple: %d' ...
            , sessionIdx ...
            , complexKsTrueId ...
            , simpleKsTrueId ...
            ) ...
        );

    xlim(ax, getParams().cc_range);
    xticks(ax, [-0.2 -0.1 0 0.1 0.2]);
    xticklabels(ax, [-200 -100 0 100 200]);

    xlabel(ax, 'Lags in ms');
    ylabel(ax, 'Amount of correlation');

    % Figure settings
    % set(0, 'defaultFigureRenderer', 'painters');
    set(ax,'TickDir','out');
    box(ax,'off');

end