function saveExemplarySimpleChannelMasks(mname, masks)
    
%     filePath = fullfile ...
%         ( cspkResultsFolder() ...
%         , sprintf ...
%             ( "exemplarySimpleChannelMasks_%s_%d.mat" ...
%             , mname ...
%             , IkUtils.now ...
%             ) ...
%         );
%         
path_ = IkUtils.getFilePath(mname);
filePath = fullfile(path_(1), sprintf("exemplarySimpleChannelMasks_%s_%s.mat", mname,IkUtils.Now)); % IK change
    save(filePath, "masks")
    
end