%% I.K. 4-6-24 
% Called by function: 
function saveBoxplots()
    
    import IkUtils.ifelse;
    
    events = ["cs", "prior", "us"];
    modulating = [true, false];
    
    outputRoot = fullfile ...
        ( Env.getBayesLabUserRoot ...
        , "TraceExperiments" ...
        , "ComplexSpikeToolkit" ...
        , "CSpk_Suite_revised" ...
        , "paperFigures" ...
        , "boxplots" ...
        );

    
    if exist(outputRoot, 'dir') ~= 7
        mkdir(outputRoot)
    end
    
    for e = events
        for m = modulating
            
            [~, ~, peakTimeBoxplotFig] = cspkPeakTimeBoxplots2 ...
                ( event = e ...
                , modulating = m ...
                );

            printFigure ...
                ( peakTimeBoxplotFig ...
                , sprintf ...
                    ( "boxplot_peakTimesSD_%s_%s" ...
                    , e ...
                    , ifelse(m, "modulating", "nonModulating") ...
                    ) ...
                , folder = outputRoot ...
                , size = [620 420] ...
                )
            
            [~, ~, cspkPeakWidthFig] = cspkPeakWidthBoxplots ...
                ( event = e ...
                , modulating = m ...
                );
            
            printFigure ...
                ( cspkPeakWidthFig ...
                , sprintf ...
                    ( "boxplot_meanPeakWidth_%s_%s" ...
                    , e ...
                    , ifelse(m, "modulating", "nonModulating") ...
                    ) ...
                , folder = outputRoot ...
                , size = [620 420] ...
                )
            
        end
    end
    
end