function saveSummaryFiguresAllMice(kwargs)
    arguments
        kwargs.mouseNames (1,:) string = [defaultMice().name];
        kwargs.outputRoot (1,1) string;
    end
    mouseNames = kwargs.mouseNames;
    
    if isfield(kwargs, "outputRoot")
        mouseWrapper = @(mname) ...
            saveSummaryFiguresMouseWrapper ...
                ( mname ...
                , outputRoot = kwargs.outputRoot ...
                );
    else
        mouseWrapper = @(mname) ...
            saveSummaryFiguresMouseWrapper ...
                ( mname ...
                );
    end
    
    arrayfun ...
        ( mouseWrapper ...
        , mouseNames ...
        )

    end