nModulatingArr = [1e0, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6];

arrayfun ...
    ( @visualize ...
    , nModulatingArr ...
    )

function visualize(nModulating)

    nUniform = 1e2;


    uniformSpikes = rand(nUniform,1);
    modulatingSpikes = 0.5 * ones(nModulating, 1);

    spikes = [uniformSpikes; modulatingSpikes];

    edges = 0:1e-2:1;
    counts = histcounts(spikes, edges);

    ax = IkUtils.initPlots;
    histogram ...
            ( ax ...
            , BinEdges = edges ...
            , BinCounts = counts ...
            , faceColor = [.75 .75 .75] ...
            , edgecolor = 'none' ... % [.6 .6 .6] ...
            )

    title ...
        ( ax ...
        , sprintf ...
        ("SD: %g, nUniform: %.0e, nModulating: %.0e" ...
            , std(spikes) ...
            , nUniform ...
            , nModulating ...
            ) ...
        )

    % plot(ax, uniformSpikes, "*")
    % plot(ax, modulatingSpikes, "s")
end