% Show type and data curation status for `mouse`.

% Copyright 2023 NarainLab
% Erasmus Medical Center, Rotterdam, The Netherlands
% v2023-01-04
% 
function showMouse(mouse)
    arguments
        mouse(1,1) struct
    end
    
    import IkUtils.sprintIndented;
    
    resultsFiles = getResultsFiles(mouse.name);
    
    simpleCurationOverview = arrayfun ...
        ( @(type, files) sprintf("%s: %s", type, files{1}.date) ...
        , string(fieldnames(resultsFiles.simple)) ...
        , struct2cell(resultsFiles.simple) ...
        );
    complexCurationOverview = arrayfun ...
        ( @(type, files) sprintf("%s: %s", type, files{1}.date) ...
        , string(fieldnames(resultsFiles.complex)) ...
        , struct2cell(resultsFiles.complex) ...
        );
    
    fprintf("------\n")
    fprintf("Mouse:\n")
    overview = sprintf ...
        ( "name: %s\ntype: %s\ncuration:\n%s" ...
        , mouse.name ...
        , mouse.type ...
        , IkUtils.sprintIndented ...
            ( sprintf ...
                ( "%s\n%s" ...
                , sprintf ...
                    ( "simple:\n%s" ...
                    , sprintIndented(strjoin(simpleCurationOverview, newline)) ...
                    ) ...
                , sprintf ...
                    ( "complex:\n%s" ...
                    , sprintIndented(strjoin(complexCurationOverview, newline)) ...
                    ) ...
                ) ...
            ) ...
        );
    
    IkUtils.printIndented(overview)
    
    
end

% function dateStr = curationTimeStamp(files)
%     
%     if isempty(files)
%         dateStr = "N/A";
%         return
%     end
%         
%     mostRecent = files(1);
%     
%     [~, fileName, ~] = fileparts(mostRecent.name);
%     fileNameC = char(fileName);
%     
%     datenum = num2str(fileNameC(end-13:end));
%     dateStr = IkUtils.ephysdatestr(datenum);
%     
% end