%% I.K. 5-6-24
% Called by function: simpleCurationSessionWrapper
function viewChannelSpikes(axs, neuronData, ircTrueId, s, mname, modulationStats, kwargs)
    arguments
        axs
        neuronData(1,1) struct
        ircTrueId(1,1) {isnumeric}
        s(1,1) {isnumeric}
        mname(1,1) string
        modulationStats(1,1) struct
        kwargs.histRanges = IkUtils.getParams().sspkRanges;
        kwargs.trialTypes = [];
    end
       
    p = IkUtils.getParams(); 
    histogramHeight = p.histogramHeight;
    histRanges = kwargs.histRanges;
    colors = getColors();
        
    psthRanges = p.psthRanges;
    
    arrayfun(@cla, axs);
    
    %% CS-aligned

    csRegion = struct ...
        ( range = histRanges.cs ...
        , stats = modulationStats.cs ...
        , color = colors.histogram.csRegion ...
        );

    usRegion = struct ...
        ( range = histRanges.us ...
        , stats = modulationStats.us ...
        , color = colors.histogram.usRegion ...
        );


    try
  title ...
        ( axs(1,1) ...
        , sprintf ...
            ( "Mouse: %s CS Aligned: Sess %d  N  %d" ...
            , neuronData.name ...
            , s ...
            , ircTrueId ...
            ) ...
        );
    catch
    title ...
        ( axs(1,1) ...
        , sprintf ...
            ( "Mouse: %s CS Aligned: Sess %d  N  %d" ...
            , mname ...
            , s ...
            , ircTrueId ...
            ) ...
        );
    end
    
    plotRasterWithHistogramAdaptedHeights ...
        ( axs(1,1) ...
        , neuronData.RasterXY_cs_filtered ... 
        , psthRanges.cs_full ...
        , histogramHeight = histogramHeight ...
        , eventTimes = p.delayEventsCs ...
        , highlightregions = [csRegion, usRegion] ...
        , trialTypes = kwargs.trialTypes ...
        );
    

    plotPsth ...
        ( axs(1,2) ...
        , neuronData.bins_cs ...
        , neuronData.psth_cs_reset_filtered ...
        , psthRanges.cs_full ...
        , p.eventTimes... 
        );
    
    % Spike raster (zoomed to CS-US interval)
    title ...
        ( axs(1,3) ...
        , sprintf ...
            ('CS Aligned Histogram: Sess %d  N  %d' ...
            , s ...
            , ircTrueId ...
            ) ...
        );
    
    plotRasterWithHistogramAdaptedHeights ...
        ( axs(1,3) ...
        , neuronData.RasterXY_cs_filtered ...
        , psthRanges.cs_zoomed ...
        , histogramHeight = histogramHeight ...
        , highlightRegions = [csRegion, usRegion] ... 
        , eventTimes = p.eventTimes...
        , trialTypes = kwargs.trialTypes ...
        );
    
    
   
