function correlate_CS_CSPK_with_prev_US(mname)
    arguments
        mname(1,1) string = "Seattle";
    end
    
    
    fileLists = getEphysFilesForMouse(mname);
    
    analyzedEphysFiles = fileLists.analyzedEphys;
    
    data = load ...
        ( fullfile ...
            ( datafiles(1).folder ...
            , datafiles(1).name ...
            ) ...
        );
    
    sessions = arrayfun ...
        ( @(sess) sess.session_modulating ...
        , data.ComplexSpikeSum ...
        , uniformoutput = false ...
        );
    
    
    
end

