% Make boxplots of standard deviations of the peaks of complex spiking activity
% across neurons. Mice are grouped by type (Delta vs Uniform)
%
function [res, axs, fig] = cspkPeakTimeBoxplots2(kwargs)
    arguments
        kwargs.event (1,1) string = "cs";
        kwargs.modulating (1,1) logical = true;
        kwargs.mouseNames (1,:) string = [defaultMice().name];
    end

    import IkUtils.flatmap;
    import IkUtils.ifelse;
    
    mouseNames = kwargs.mouseNames;
    
    peakDelayData = flatmap ...
        ( @(mname) computeCspkTuningDelays ...
                    ( mname ...
                    , modulating = kwargs.modulating ...
                    , event = kwargs.event ...
                    ) ...
        , mouseNames ...
        );
    
    deltaMask = strcmpi([peakDelayData.type], "delta");
    uniformMask = not(deltaMask);
    
    [axs, fig] = IkUtils.initPlots([1 5], layout = {{1 1 1 3} {1 4 1 2}});
    
    ylabel(axs(1), "SD of peak times across neurons") ...

    computeDelaySDs = @(delayData) arrayfun ...
        ( @(mouseData) std(mouseData.delays) ...
        , delayData ...
        );

    deltaData = computeDelaySDs(peakDelayData(deltaMask));
    deltaSubjects = [peakDelayData(deltaMask).mname];
    uniformData = computeDelaySDs(peakDelayData(uniformMask));
    uniformSubjects = [peakDelayData(uniformMask).mname];
    
    [h, p, ci, stats] = ttest2(deltaData, uniformData)
    
    tTestResult = ...
            struct ...
                ( h = h ...
                , p = p ...
                , ci = ci ...
                , stats = stats ...
                );

    mkDeltaVsUniformBoxPlot ...
        ( axs ...
        , deltaData ...
        , uniformData ...
        , sprintf ...
            ( "%s - %s" ...
            , kwargs.event ...
            , ifelse(kwargs.modulating, "modulating", "non modulating") ...
            ) ...
        , deltaSubjects = deltaSubjects ...
        , uniformSubjects = uniformSubjects ...
        , tTestResult = tTestResult ...
        )
    
    res = struct ...
        ( delta = deltaData ...
        , uniform = uniformData ...
        , event  = kwargs.event ...
        , modulating = kwargs.modulating ...
        , ttest = tTestResult ...
        );


end
