function folder = cspkResultsFolder()
P = IkUtils.getParams(); % IK change
%     folder = fullfile ...  % IK change
%         ( Env.getBayesLabUserRoot() ...
%         , "TraceExperiments" ...
%         , "ComplexSpikeToolkit" ...
%         , "CSpk_Suite_revised" ...
%         , "curationResults" ...
%         );
folder = fullfile(P.dirHome); % IK change
end