function folder = cspkPaperFigsFolder(num)
    
    import IkUtils.ifelse;
    
    if nargin > 0
        subfolder = num2str(num);
    else
        subfolder = "";
    end
    
    folder = fullfile ...
        ( Env.getBayesLabUserRoot ...
        , "TraceExperiments" ...
        , "ComplexSpikeToolkit" ...
        , "CSpk_Suite_revised" ...
        , "paperFigures" ...
        , subfolder ...
        );
end