function rawResult = loadComplexCurationResultRaw(mname, kwargs)
    arguments
        mname (1,1) string
        kwargs.onlyLatest (1,1) {islogical} = true;
    end
   
    args = ...
        { mname ...
        , 'onlyLatest', kwargs.onlyLatest ...
        };
    
    rawResult = struct ...
        ( complex = loadComplexMasks(args{:}) ...
        , exemplary = loadExemplaryComplexChannelMasks(args{:}) ...
        , modulation = loadComplexChannelModulationMasks(args{:}) ...
        );
    
%     if numel(rawResult.complexMasks) ~= numel(rawResult.exemplaryMasks) ...
%         || numel(rawResult.complexMasks) ~= numel(rawResult.modulationMasks)
%         warning ...
%             ( "unequal number of session in previous curation masks:\n" ...
%             + "\tcomplex: %d\n" ...
%             + "\texemplary: %d\n" ...
%             + "\tmodulation: %d\n" ...
%             + "\nIt might be best to abort and fix this issue before continuing." ...
%             , numel(rawResult.complexMasks) ...
%             , numel(rawResult.exemplaryMasks) ...
%             , numel(rawResult.modulationMasks) ...
%             )
%         keyboard
%     end
    
    
end