function mkDeltaVsUniformBoxPlot(axs, deltaData, uniformData, titleString, kwargs)
    arguments
        axs (1,:) matlab.graphics.axis.Axes
        deltaData (1,:) {isnumeric}
        uniformData (1,:) {isnumeric}
        titleString (1,1) string = "";
        kwargs.deltaSubjects (1,:) string = repmat("", size(deltaData));
        kwargs.uniformSubjects (1,:) string = repmat("", size(uniformData));
        kwargs.tTestResult struct
    end

    c = getColors();
    
    title(axs(1), sprintf("%s", titleString))

    boxchart ...
        ( axs(1) ...
        , repmat(1, size(deltaData)) ...
        , deltaData ...
        , boxfacecolor = c.c_delta ...
        );
    boxchart ...
        ( axs(1) ...
        , repmat(2, size(uniformData)) ...
        , uniformData ...
        , boxfacecolor = c.c_uniform ...
        );

    plotPoints = @(ax, x, ydata, subjects, color) ...
        arrayfun ...
            ( @(y, subject) ...
                line ...
                    ( ax ...
                    , x, y ...
                    , marker = '.' ...
                    , MarkerSize = 20 ...
                    , Color = color ...
                    , userdata = subject ...
                    ) ...
            , ydata ...
            , subjects ...
            );

    plotPoints(axs(1), 1, deltaData, kwargs.deltaSubjects, c.c_delta);
    plotPoints(axs(1), 2, uniformData, kwargs.uniformSubjects, c.c_uniform);
    
    axs(1).XAxis.TickValues = [1 2];
    axs(1).XAxis.TickLabels = ["Delta", "Uniform"];
    
    %% display t-test results
    
    if isfield(kwargs, "tTestResult")
        text ...
            ( axs(2) ...
            , 1/10, 3/4 ...
            ,  IkUtils.sprintStruct(kwargs.tTestResult, rootName = "t-test") ...
            , fontsize = 11 ...
            )
        axs(2).Visible = false;
%         keyboard
    end
        
    end