function viewComplexChannel ...
                        ( axs ...
                        , channelData, ksTrueId ...
                        , histStats ...
                        , sSpkData, simpleKsTrueId ...
                        , mname ...
                        , sessionIdx ...
                        , kwargs ...
                        )
    arguments
        axs
        channelData
        ksTrueId 
        histStats 
        sSpkData
        simpleKsTrueId 
        mname 
        sessionIdx 
        kwargs.trialTypes = [];
    end
                    
        viewChannelSpikes ...
            ( axs.neuronAxs ...
            , channelData ...
            , ksTrueId ...
            , sessionIdx ...
            , mname ...
            , histStats ...
            , trialTypes = kwargs.trialTypes ...
            );

        contaminationFigures2 ...
            ( axs.contaminAx ...
            , computeContamination(channelData) ...
            );

        plotCrossCorrelation2 ...
            ( axs.crossCorrAx ...
            , channelData, ksTrueId ...
            , sSpkData, simpleKsTrueId ...
            , mname ...
            , sessionIdx ...
            );
        
end


