function visualizeCspkTuningAcrossMice(mice, kwargs)
    arguments 
        mice (1,:) string = [paperFiguresMice().name];
        kwargs.event (1,1) string = "prior";
        kwargs.saveFigures (1,1) logical = false;
    end

    assert ...
        ( any(strcmpi(kwargs.event, ["cs", "prior", "us"])) ...
        , "Invalid event, should be 'cs', 'prior', or 'us'" ...
        )
    
    event = lower(kwargs.event);
    
    import IkUtils.visualization.excludeFromLegend;
    import IkUtils.flatmap;
    
    p = getParams();
    
    rangeMin = p.cspkRanges.(event).min * 1000;
    rangeMax = p.cspkRanges.(event).max * 1000;
    
    peakDelayData = arrayfun ...
        ( @(mname) computeCspkTuningDelays ...
            ( mname ...
            , modulating = true ...
            , event = event ...
            , type = "uniform" ...
            ) ...
        , mice ...
        );
    
    [delayAx, delayFig] = IkUtils.initPlots([1 1]);
    title(delayAx, sprintf("%s CSpk modes", event))
    ylabel(delayAx, "CSpk histogram mode [ms]")
    
    [delays, delayLabels] = unpack(peakDelayData, "delays");
%     anova1(delays, delayLabels);
    
    mkBoxCharts(delayAx, peakDelayData, "delays")
    touchupGraph(delayAx, peakDelayData, "delays", rangeMin, rangeMax)
%     ylim(delayAx, [rangeMin rangeMax])
    
    
    histWidthData = arrayfun ...
        ( @(mname) computeCspkTuningWidths ...
            ( mname ...
            , modulating = true ...
            , event = event ...
            , type = "uniform" ...
            ) ...
        , mice ...
        );
    
    [widthAx, widthFig] = IkUtils.initPlots([1 1]);
    title(widthAx, sprintf("%s CSpk widths", event))
    ylabel(widthAx, "CSpk histogram SD [ms]")
    
    [widths, widthLabels] = unpack(histWidthData(:), "sds");
%     anova1(widths, widthLabels);

    mkBoxCharts(widthAx, histWidthData, "sds")
    touchupGraph(widthAx, histWidthData, "sds", 0, rangeMax-rangeMin)
%     ylim(widthAx, [0 (rangeMax-rangeMin + 10)])

    
    %% Saving
    
    if kwargs.saveFigures
        
        figSize = [560 580];
        
        exportFolder = fullfile ...
                ( Env.getBayesLabUserRoot() ...
                , "TraceExperiments" ...
                , "Cerebellar Priors and Complex Spikes" ...
                , "DefaultExport" ...
                , IkUtils.todayStr() ...
                );
        mkdir(exportFolder)

        printFigure ...
            ( delayFig ...
            , sprintf("%sCSpkDelays_across_mice", event) ...
            , folder = exportFolder ...
            , size = figSize ...
            )
         printFigure ...
            ( widthFig ...
            , sprintf("%sCSpkWidths_across_mice", event) ...
            , folder = exportFolder ...
            , size = figSize ...
            )
    end
    
    %% Utils
    
    function [values, labels] = unpack(data, dataField)
        
        labels = flatmap ...
            ( @(dat) repmat(dat.mname, size(dat.(dataField))) ...
            , data ...
            );
        values = [data.(dataField)];
        
    end

    function mkBoxCharts(ax, miceData, dataField)
        
        boxChartColor = [.7 .7 .7];
        
        xLimits = [0.5 numel(miceData)+0.5];
%         yMax = max([miceData.(dataField)]);
        
        mouseMeans = arrayfun ...
            ( @(dat) mean(dat.(dataField)) ...
            , miceData ...
            );
        grandMean = mean(mouseMeans);

        excludeFromLegend ...
            ( line ...
                ( ax ...
                , [0 numel(miceData)+1] ...
                , repmat(grandMean, size(ax.XLim)) ...
                , linestyle = '--' ...
                , color = [.7 .7 .7] ...
                ) ...
            )

        mkBoxChart = @(x, data) ...
            boxchart ...
                ( ax ...
                , repmat(x, size(data.(dataField))) ...
                , data.(dataField) ...
                , displayname = data.mname ...
                , markerstyle = 'x' ...
                , jitteroutliers = false ...
                , notch = false ...
                , boxfacealpha  = .2 ...
                , boxfacecolor = boxChartColor ...
                , whiskerlinecolor = boxChartColor - .3 ...
                , markercolor = boxChartColor - .3 ...
                );

        arrayfun ...
            ( mkBoxChart ...
            , 1:numel(miceData) ...
            , miceData ...
            )

%         legend(ax)
        xlim(ax, xLimits)
        ax.XTick = 1:numel(miceData);
        ax.XTickLabel = [miceData.mname];

    end
    
    function touchupGraph(ax, miceData, dataField, rangeMin, rangeMax)
        
        ylim(ax, [rangeMin rangeMax+5])
        nTotal = numel([miceData.(dataField)]);

        subtitle(ax, sprintf("N=%d", nTotal))
        
        showN = @(x, data) ...
            text ...
                ( ax ...
                , x, max(data.(dataField)) + 3 ...
                , sprintf("N=%d", numel(data.(dataField))) ...
                , HorizontalAlignment = 'center' ...
                , color = [.3 .3 .3] ...
                );
        
        arrayfun ...
            ( showN ...
            , 1:numel(miceData) ...
            , miceData ...
            );
        
    end
end