function colors = getColors()

    ColDist = ...
        [ rgb('DarkGrey') ... % IK change
        ; IkUtils.color.lighten(rgb('DarkViolet')) ...
        ; rgb('Orange') ...
        ];

% ColDist(2,1:3)   = rgb('PaleTurquoise');
% ColDist(3,1:3)   = rgb('MediumAquamarine');
% ColDist(4,1:3)   = rgb('DarkTurquoise');
% ColDist(5,1:3)   = rgb('LightSeaGreen');
% ColDist(6,1:3)   = rgb('Teal');
% ColDist(1,1:3)   = rgb('DarkGray');
% Colors
colors = struct ...
    ( csonlyDelt = rgb('LightGray') ...
    , csonlyDist = rgb('DarkGray') ...
    , ColDist = ColDist ...
    , c_delta = rgb('Violet') ...
    , c_blue = rgb('Teal') ...
    , c_grey = [0.3882    0.3686    0.3686] ...
    , c_green = [0 1 0] ...
    , histogram = struct ...
        ( csRegion = IkUtils.color.lighten(rgb('DeepSkyBlue')) ... % IK change
        , usRegion = IkUtils.color.lighten(rgb('ForestGreen')) ...
        ) ...
    , gold = [.85 .8 .4]...
    , exemplary = [0.7581    0.9576    0.8081] ...[0.8081    0.9576    0.8081] ...[0.7040    0.9386    0.7040] ...
    );

end