% Detect switch sessions for mice trained on different condition types across
% sessions.

function [startSession, endSession] = getStartEndSessions(data, type, startSession)
    
nSessions = length(data);

switchSessions = detectSwitchSessions(data);
switchSessionMask = [switchSessions.mask];
switchSessionTypes = [switchSessions.type];
DUswitchSessionMask = switchSessionMask(:) & switchSessionTypes(:) == "DU";
UDswitchSessionMask = switchSessionMask(:) & switchSessionTypes(:) == "UD";
DUfirstSwitchSession = find(DUswitchSessionMask == 1, 1);
UDfirstSwitchSession = find(UDswitchSessionMask == 1, 1);

if type == "Delta"
     if ~isempty(UDfirstSwitchSession) && ...
            ( ...
            (~isempty(DUfirstSwitchSession) && UDfirstSwitchSession < DUfirstSwitchSession) ...
            || ...
            (isempty(DUfirstSwitchSession)) ...
            )
        startSession = UDfirstSwitchSession;
    else
        startSession = startSession;
    end
    if ~isempty(DUfirstSwitchSession) &&...
            ( ...
            (~isempty(UDfirstSwitchSession) && UDfirstSwitchSession > DUfirstSwitchSession ) ...
            || ...
            (isempty(UDfirstSwitchSession)) ...
            )
        endSession = DUfirstSwitchSession - 1;
    else
        endSession = nSessions;
    end
elseif type == "Uniform"
    if ~isempty(DUfirstSwitchSession) && ...
            ( ...
            (~isempty(UDfirstSwitchSession) && DUfirstSwitchSession < UDfirstSwitchSession) ...
            || ...
            (isempty(UDfirstSwitchSession)) ...
            )
        startSession = DUfirstSwitchSession;
    else
        startSession = startSession;
    end
    if ~isempty(UDfirstSwitchSession) &&...
            ( ...
            (~isempty(DUfirstSwitchSession) && DUfirstSwitchSession > UDfirstSwitchSession ) ...
            || ...
            (isempty(DUfirstSwitchSession)) ...
            )
        endSession = UDfirstSwitchSession - 1;
    else
        endSession = nSessions;
    end
elseif type == "DEUN"
    if ~isempty(UDfirstSwitchSession) ...
        && (~isempty(DUfirstSwitchSession) && UDfirstSwitchSession < DUfirstSwitchSession) ...
        || (isempty(DUfirstSwitchSession))
            
        startSession = UDfirstSwitchSession;
    else
        startSession = startSession;
    end
    if ~isempty(UDfirstSwitchSession) ...
            && (~isempty(DUfirstSwitchSession) && DUfirstSwitchSession < UDfirstSwitchSession ) ...
            || (isempty(DUfirstSwitchSession))
        endSession = UDfirstSwitchSession - 1;
    else
        endSession = nSessions;
    end    
end

