function [masks, dates] = loadExemplaryMasks(mname, kwargs)
    arguments
        mname(1,1) string
        kwargs.onlyLatest(1,1) logical {islogical} = true;
    end

    patternTemplate = sprintf ...
        ( "exemplary%%sChannelMasks_%s_*.mat" ...
        , mname ...
        );
    
    filePatterns = struct ...
        ( complex = sprintf(patternTemplate, "Complex") ...
        , simple = sprintf(patternTemplate, "Simple") ...
        );
    
    loadFn = @() structfun ...
            ( @(filePattern) ...
                IkUtils.io.loadTimestampedFiles ...
                    ( filePattern ...
                    , onlyLatest = kwargs.onlyLatest ...
                    , folder = cspkResultsFolder() ...
                    , uniformData = false ... % channel masks are of varying length
                    ) ...
            , filePatterns ...
            , UniformOutput = false ...
            );
    
    if nargout < 2
        % Don't compute date strings if they weren't requested by the
        % caller
        masks = loadFn();
    else
        [masks, dates] = loadFn();
    end
    
end