function mouseList = paperFiguresMice()
    
    mouseList = ...
        [ struct( name = "Seattle" ...
                , type = "Uniform" ...
                ) ...
        , struct( name = "Yosemite" ...
                , type = "Uniform" ...
                ) ...
        , struct( name = "Flint" ...
                , type = "DEUN" ...
                ) ...
        , struct( name = "Newark" ... % Recorded on Uniform (IK Q: trained on Delta or on Uniform?)
                , type = "Uniform" ...
                ) ...
        , struct( name = "Zachary" ...
                , type = "Uniform" ...
                ) ...
        , struct( name = "ReserveMouse3" ...
                , type = "DEUN" ...
                ) ...
        ];
    
end