function plotRasterWithHistogram(ax, rasterXY, range, kwargs)
    arguments
        ax
        rasterXY
        range
        kwargs.histogramHeight(1,1) double {isnumeric} = 15;
        kwargs.highlightRegions(1,:) struct = struct.empty
        kwargs.nTrials(1,1) double {isnumeric} = 220; % IK change
        kwargs.eventTimes(1,:) double {isnumeric} = [];
        kwargs.trialTypes = [];
    end
    
    %% Histogram

    xlabel(ax, "time [ms]")
    ax.YAxis.TickValues = [];
    ax.XAxis.TickValues = [0 200 350 500];
    ylabel(ax, "Sorted trials")
    
    textHeight = 5;
    
    spikeTimes = rasterXY(1,1:2:end) * 1000;
    
    binWidth = IkUtils.getParams().BinW;
    edges = (range.min:binWidth:range.max) * 1000;
    
    rangeMask = spikeTimes >= range.min * 1000 & spikeTimes <= range.max * 1000;
   
    counts = histcounts(spikeTimes(rangeMask), edges);
    
    maxCount = max(counts);
    if any(maxCount == [0, nan, inf])
        normalization = 1;
    else
        normalization = maxCount;
    end
    
    IkUtils.histogramIK ... % IK change
        ( ax ...
        , BinEdges = edges ... 
        , BinCounts = counts / normalization * kwargs.histogramHeight ...
        , faceColor = [.75 .75 .75] ...
        , edgecolor = 'none' ... % [.6 .6 .6] ...
        )
    
    yMax = kwargs.nTrials ...
        + kwargs.histogramHeight ...
        + (numel(kwargs.highlightRegions)+1) * textHeight ...
        ;
    
    arrayfun ...
        ( @(spec) highlightRegionHist(spec, normalization) ...
        , kwargs.highlightRegions ...
        )

    arrayfun ...
        ( @(i, spec) highlightRegionText(i, spec.stats) ...
        , 1:numel(kwargs.highlightRegions) ...
        , kwargs.highlightRegions ...
        );
    
    function highlightRegionHist(spec, normalization)
        
        if isfield(spec, "color")
            colorArg = {"facecolor", spec.color};
        else
            colorArg = {};
        end

        x1 = spec.range.min * 1000;
        x2 = spec.range.max * 1000;
        y1 = kwargs.histogramHeight;
        y2 = y1 + kwargs.nTrials;
        patch ...
            ( ax ...
            , [x1 x1 x2 x2] ...
            , [y1 y2 y2 y1] ...
            , spec.color ... % IK change. TODO: Check why prev code didn't work and change to right color.
            , EdgeColor = 'none' ...
            , FaceAlpha = 0.2 ...
            )
        
        regionEdges = (spec.range.min:binWidth:spec.range.max) * 1000;

        regionMask = spikeTimes >= spec.range.min * 1000 & spikeTimes <= spec.range.max * 1000;
   
        regionCounts = histcounts(spikeTimes(regionMask), regionEdges);
        
        IkUtils.histogramIK ... % IK change
            ( ax ...
            , colorArg{:} ...
            , BinEdges = regionEdges ...
            , BinCounts = regionCounts / normalization * kwargs.histogramHeight ...
            , facealpha = 1 ...
            , edgecolor = 'none' ... % [.75 .75 .75] ...
            );
        
    end
    
    function highlightRegionText(index, stats)

        y = yMax ...
            - 5 * index ...
            ;
        
        text ...
            ( ax ...
            , (range.min + (range.max - range.min)*0.1) * 1000 ...
            , y ...
            , sprintf("Pk: %d", stats.maxAmp) ...
            );

        text ...
            ( ax ...
            , (range.min + (range.max - range.min)*0.3) * 1000 ...
            , y ...
            , sprintf('PT: %.4f', stats.maxAmpTime) ...
            );

        text ...
            ( ax ...
            , (range.min + (range.max - range.min)*0.7) * 1000 ...
            , y ...
            , sprintf('SD: %.4f', stats.sd) ...
            );

    end
    
    %% Raster
    
    plot ...
        ( ax ...
        , rasterXY(1,:) * 1000 ...
        , rasterXY(2,:) + kwargs.histogramHeight ...
        , Color = [.2 .2 .2] ...
        );
    
    eventMn = kwargs.histogramHeight + 1;
    eventMx = eventMn + kwargs.nTrials - 1;
    
    arrayfun ...
        ( @(eventTime) ...
            plot ...
                ( ax ...
                , [eventTime eventTime] * 1000, [eventMn, eventMx] ...
                , '--' ...
                , color = [.5 .5 .5] ...
                ) ...
        , kwargs.eventTimes ...
        );
    
    xlim(ax, [range.min range.max] * 1000);
    ylim(ax, [0 yMax]);
    
    %% Plot trial type colors
    
    if ~isempty(kwargs.trialTypes)
        plotTrialTypeColors ...
            ( ax ...
            , sort(kwargs.trialTypes) ...
            , kwargs.histogramHeight + 1 ...
            , kwargs.histogramHeight + numel(kwargs.trialTypes) ...
            , ax.XLim(1) ...
            , ax.XLim(1) + (ax.XLim(2) - ax.XLim(1)) / 80 ...
            )
    end
    
    
end
    
function plotTrialTypeColors(ax, trialTypes, yMin, yMax, xMin, xMax)
    
    height = yMax - yMin;
    types = unique(trialTypes);
    cumFrac = 0;
    
    allColors = getColors();
     
   if numel(types) == 2
       % Delta
       colors = [allColors.csonlyDelt; allColors.c_delta];
   else
       colors = allColors.ColDist;               
   end
    
    for i = 1:numel(types)
        type = types(i);
        
        frac = sum(trialTypes == types(i)) / numel(trialTypes);
        y1 = yMin + height * cumFrac;
        y2 = yMin + height * (cumFrac + frac);
        
        
       cumFrac = cumFrac + frac;
       
       
       patch ...
            ( ax ...
            , [xMin xMin xMax xMax] ...
            , [y1 y2 y2 y1] ...
            , colors(type+1, :) ...
            , EdgeColor = 'none' ...
            , FaceAlpha = 1 ...
            )
        
    end
    
end