function [axs, figs, types] = plotSummaryFiguresMUTvsWT(mname, type, kwargs)
    arguments
        mname (1,1) string = "Shank2KOMUT"
        type (1,1) string = getMouseType(mname);
        kwargs.modulating (1,1) logical
        kwargs.event (1,1) string
    end


    p = IkUtils.getParams();

    switch type %lower(type)
        case "Shank2KOMUT"
            sessionIdcs = [1,2]; %splitSessionsByType(mname).uniform;
            types = "Shank2KOMUT";
        case "Shank2KOWT"
            sessionIdcs = [1,2]; %splitSessionsByType(mname).delta;
            types = "Shank2KOWT";
        otherwise
            error("Unknown session type: %s", type)
    end

    allStatsMUT = histStatsMouseWrapper ...
        ( "Shank2KOMUT" ...
        , event = kwargs.event ...
        , modulating = kwargs.modulating ...
        );

    allStatsWT = histStatsMouseWrapper ...
        ( "Shank2KOWT" ...
        , event = kwargs.event ...
        , modulating = kwargs.modulating ...
        );

    cs_facilitation_mask_MUT = [allStatsMUT.cs.cs_facilitation] == 1;
    cs_facilitation_mask_WT = [allStatsWT.cs.cs_facilitation] == 1;
    cs_suppression_mask_MUT = [allStatsMUT.cs.cs_suppression] == 1;
    cs_suppression_mask_WT = [allStatsWT.cs.cs_suppression] == 1;
    non_mod_mask_cs_MUT = [allStatsMUT.cs.cs_facilitation] == 0 & [allStatsMUT.cs.cs_suppression] == 0;
    non_mod_mask_cs_WT = [allStatsWT.cs.cs_facilitation] == 0 & [allStatsWT.cs.cs_suppression] == 0;

    us_facilitation_mask_MUT = [allStatsMUT.us.us_facilitation] == 1;
    us_facilitation_mask_WT = [allStatsWT.us.us_facilitation] == 1;
    us_suppression_mask_MUT = [allStatsMUT.us.us_suppression] == 1;
    us_suppression_mask_WT = [allStatsWT.us.us_suppression] == 1;
    non_mod_mask_us_MUT = [allStatsMUT.us.us_facilitation] == 0 & [allStatsMUT.us.us_suppression] == 0;
    non_mod_mask_us_WT = [allStatsWT.us.us_facilitation] == 0 & [allStatsWT.us.us_suppression] == 0;

    %% CS

    %% covariance
    figure()
    boxplot_data = [ ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).cov] ...
        [allStatsWT.cs(non_mod_mask_cs_WT).cov] ...
        [allStatsMUT.cs(cs_facilitation_mask_MUT).cov] ...
        [allStatsWT.cs(cs_facilitation_mask_WT).cov] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).cov]; ...
        [allStatsWT.cs(non_mod_mask_cs_WT).cov]; ...  
        [allStatsMUT.cs(cs_facilitation_mask_MUT).cov]; ...
        [allStatsWT.cs(cs_facilitation_mask_WT).cov] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('CV')
    xlim([0.002 0.004]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('CV spk times CS MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallCVcsMUTvsWT.png'), 'png')

    %% local covariance
    figure()
    boxplot_data = [ ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).meanLcov] ...
        [allStatsWT.cs(non_mod_mask_cs_WT).meanLcov] ...
        [allStatsMUT.cs(cs_facilitation_mask_MUT).meanLcov] ...
        [allStatsWT.cs(cs_facilitation_mask_WT).meanLcov] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).meanLcov]; ...
        [allStatsWT.cs(non_mod_mask_cs_WT).meanLcov]; ... 
        [allStatsMUT.cs(cs_facilitation_mask_MUT).meanLcov]; ...
        [allStatsWT.cs(cs_facilitation_mask_WT).meanLcov] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('LCV')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('LCV spk times CS MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallLCVcsMUTvsWT.png'), 'png')
    
    %% ISI
    figure()
    boxplot_data = [ ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).meanISIroi] ...
        [allStatsWT.cs(non_mod_mask_cs_WT).meanISIroi] ...
        [allStatsMUT.cs(cs_facilitation_mask_MUT).meanISIroi] ...
        [allStatsWT.cs(cs_facilitation_mask_WT).meanISIroi] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).meanISIroi]; ...
        [allStatsWT.cs(non_mod_mask_cs_WT).meanISIroi]; ...  
        [allStatsMUT.cs(cs_facilitation_mask_MUT).meanISIroi]; ...
        [allStatsWT.cs(cs_facilitation_mask_WT).meanISIroi] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('ISI')
    xlim([-0.0001 0.0005]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('ISI spk times CS MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallISIcsMUTvsWT.png'), 'png')
   
    %% rate
    figure()
    boxplot_data = [ ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).rate] ...
        [allStatsWT.cs(non_mod_mask_cs_WT).rate] ...
        [allStatsMUT.cs(cs_facilitation_mask_MUT).rate] ...
        [allStatsWT.cs(cs_facilitation_mask_WT).rate] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).rate]; ...
        [allStatsWT.cs(non_mod_mask_cs_WT).rate]; ...    
        [allStatsMUT.cs(cs_facilitation_mask_MUT).rate]; ...
        [allStatsWT.cs(cs_facilitation_mask_WT).rate] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('freq')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('freq spk times CS MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallfreqcsMUTvsWT.png'), 'png')

   

    %% maxAmpTime
    figure()
    boxplot_data = [ ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).maxAmpTime] ...
        [allStatsWT.cs(non_mod_mask_cs_WT).maxAmpTime] ...
        [allStatsMUT.cs(cs_facilitation_mask_MUT).maxAmpTime] ...
        [allStatsWT.cs(cs_facilitation_mask_WT).maxAmpTime] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).maxAmpTime]; ...
        [allStatsWT.cs(non_mod_mask_cs_WT).maxAmpTime]; ... 
        [allStatsMUT.cs(cs_facilitation_mask_MUT).maxAmpTime]; ...
        [allStatsWT.cs(cs_facilitation_mask_WT).maxAmpTime] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('PT')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('PT spk times CS MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallPTcsMUTvsWT.png'), 'png')

    
    %% SD
    figure()
    boxplot_data = [ ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).sd] ...
        [allStatsWT.cs(non_mod_mask_cs_WT).sd] ...
        [allStatsMUT.cs(cs_facilitation_mask_MUT).sd] ...
        [allStatsWT.cs(cs_facilitation_mask_WT).sd] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.cs(non_mod_mask_cs_MUT).sd]; ...
        [allStatsWT.cs(non_mod_mask_cs_WT).sd]; ...    
        [allStatsMUT.cs(cs_facilitation_mask_MUT).sd]; ...
        [allStatsWT.cs(cs_facilitation_mask_WT).sd] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('SD')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('SD spk times CS MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallSDcsMUTvsWT.png'), 'png')

    %% US

    %% covariance
    figure()
    boxplot_data = [ ...
        [allStatsMUT.us(non_mod_mask_us_MUT).cov] ...
        [allStatsWT.us(non_mod_mask_us_WT).cov] ...
        [allStatsMUT.us(us_facilitation_mask_MUT).cov] ...
        [allStatsWT.us(us_facilitation_mask_WT).cov] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.us(non_mod_mask_us_MUT).cov]; ...
        [allStatsWT.us(non_mod_mask_us_WT).cov]; ...  
        [allStatsMUT.us(us_facilitation_mask_MUT).cov]; ...
        [allStatsWT.us(us_facilitation_mask_WT).cov] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('CV')
%     xlim([0.002 0.004]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('CV spk times US MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallCVusMUTvsWT.png'), 'png')

    %% local covariance
    figure()
    boxplot_data = [ ...
        [allStatsMUT.us(non_mod_mask_us_MUT).meanLcov] ...
        [allStatsWT.us(non_mod_mask_us_WT).meanLcov] ...
        [allStatsMUT.us(us_facilitation_mask_MUT).meanLcov] ...
        [allStatsWT.us(us_facilitation_mask_WT).meanLcov] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.us(non_mod_mask_us_MUT).meanLcov]; ...
        [allStatsWT.us(non_mod_mask_us_WT).meanLcov]; ... 
        [allStatsMUT.us(us_facilitation_mask_MUT).meanLcov]; ...
        [allStatsWT.us(us_facilitation_mask_WT).meanLcov] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('LCV')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('LCV spk times US MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallLCVusMUTvsWT.png'), 'png')
    
    %% ISI
    figure()
    boxplot_data = [ ...
        [allStatsMUT.us(non_mod_mask_us_MUT).meanISIroi] ...
        [allStatsWT.us(non_mod_mask_us_WT).meanISIroi] ...
        [allStatsMUT.us(us_facilitation_mask_MUT).meanISIroi] ...
        [allStatsWT.us(us_facilitation_mask_WT).meanISIroi] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.us(non_mod_mask_us_MUT).meanISIroi]; ...
        [allStatsWT.us(non_mod_mask_us_WT).meanISIroi]; ...  
        [allStatsMUT.us(us_facilitation_mask_MUT).meanISIroi]; ...
        [allStatsWT.us(us_facilitation_mask_WT).meanISIroi] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('ISI')
    xlim([-0.0001 0.0005]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('ISI spk times US MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallISIusMUTvsWT.png'), 'png')
   
    %% rate
    figure()
    boxplot_data = [ ...
        [allStatsMUT.us(non_mod_mask_us_MUT).rate] ...
        [allStatsWT.us(non_mod_mask_us_WT).rate] ...
        [allStatsMUT.us(us_facilitation_mask_MUT).rate] ...
        [allStatsWT.us(us_facilitation_mask_WT).rate] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.us(non_mod_mask_us_MUT).rate]; ...
        [allStatsWT.us(non_mod_mask_us_WT).rate]; ...    
        [allStatsMUT.us(us_facilitation_mask_MUT).rate]; ...
        [allStatsWT.us(us_facilitation_mask_WT).rate] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('freq')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('freq spk times US MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallfrequsMUTvsWT.png'), 'png')

   

    %% maxAmpTime
    figure()
    boxplot_data = [ ...
        [allStatsMUT.us(non_mod_mask_us_MUT).maxAmpTime] ...
        [allStatsWT.us(non_mod_mask_us_WT).maxAmpTime] ...
        [allStatsMUT.us(us_facilitation_mask_MUT).maxAmpTime] ...
        [allStatsWT.us(us_facilitation_mask_WT).maxAmpTime] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.us(non_mod_mask_us_MUT).maxAmpTime]; ...
        [allStatsWT.us(non_mod_mask_us_WT).maxAmpTime]; ... 
        [allStatsMUT.us(us_facilitation_mask_MUT).maxAmpTime]; ...
        [allStatsWT.us(us_facilitation_mask_WT).maxAmpTime] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('PT')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('PT spk times US MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallPTusMUTvsWT.png'), 'png')

    
    %% SD
    figure()
    boxplot_data = [ ...
        [allStatsMUT.us(non_mod_mask_us_MUT).sd] ...
        [allStatsWT.us(non_mod_mask_us_WT).sd] ...
        [allStatsMUT.us(us_facilitation_mask_MUT).sd] ...
        [allStatsWT.us(us_facilitation_mask_WT).sd] ...
        ];
    boxplot_data_cell = { ...
        [allStatsMUT.us(non_mod_mask_us_MUT).sd]; ...
        [allStatsWT.us(non_mod_mask_us_WT).sd]; ...    
        [allStatsMUT.us(us_facilitation_mask_MUT).sd]; ...
        [allStatsWT.us(us_facilitation_mask_WT).sd] ...
        };
    grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
    boxplot_labels = {'nonMUT','nonWT','facMUT','facWT'};
    boxplot_labels_new = {boxplot_labels{unique(grp)}};
    colors = [[0.7 0 0]; [0 0 0.7];[0.7 0 0];[0 0 0.7]];
    boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal','colors',colors)
    ylabel('Type')
    xlabel('SD')
%     xlim([-0.0001 0.001]);
    set(gca,'tickdir','out','box','off');
    title(sprintf('SD spk times US MUT vs WT'))

    saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotallSDusMUTvsWT.png'), 'png')
    

%     figure()
%     boxplot_data = [[allStats.us(non_mod_mask_us).maxAmpTime] [allStats.us(us_facilitation_mask).maxAmpTime] [allStats.us(us_suppression_mask).minAmpTime]];
%     boxplot_data_cell = {[allStats.us(non_mod_mask_us).maxAmpTime]; [allStats.us(us_facilitation_mask).maxAmpTime]; [allStats.us(us_suppression_mask).minAmpTime]};
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'Non modulating', 'US facilitation', 'US suppression'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Modulation type')
%     xlabel('Peak Time')
%     xlim([0 0.35]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('Peak time neuron frequency per US modulation type %s', mname))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotUS%s.png', mname), 'png')
% 
% %     allStats.cs.cov = cov(allStats.cs.spikeTimes);
% % % Initialize covariance matrix container
% % num_neurons = length(allStats.cs);
% % % allStats.cs.cov = cell(num_neurons, 1);
% % 
% % % Compute covariance matrix for each neuron
% % for i = 1:num_neurons
% %     spike_times = allStats.cs(i).spikeTimes; % Spike times for current neuron
% %     spike_counts = length(spike_times); % Number of spikes for current neuron
% %     
% %     % If there are enough spikes for covariance calculation
% %     if spike_counts > 1
% %         % Compute the covariance matrix
% %         cov_matrix = cov(spike_times);
% %     else
% %         % If there is only one spike, covariance matrix is not defined
% %         cov_matrix = NaN;
% %     end
% %     
% %     % Store the covariance matrix for current neuron
% %     allStats.cs(i).cov = cov_matrix;
% % end
% 
%     figure()
%     boxplot_data = [[allStats.cs(non_mod_mask_cs).cov] [allStats.cs(cs_facilitation_mask).cov] [allStats.cs(cs_suppression_mask).cov]];
%     boxplot_data_cell = {[allStats.cs(non_mod_mask_cs).cov]; [allStats.cs(cs_facilitation_mask).cov]; [allStats.cs(cs_suppression_mask).cov]};
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'Non mod','CS fac', 'CS sup'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Modulation type')
%     xlabel('Peak Time')
%     xlim([0 0.005]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('Cov neurons per CS mod type %s', mname))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotCovCS%s.png', mname), 'png')

    %     if kwargs.saveSummaryFigures
    %         fname = sprintf('SummaryFigureNonMod%s.eps',kwargs.mname);
    %         saveFigures(gca, fname);
    %         fname2 = sprintf('SummaryFigureNonMod%s.fig',kwargs.mname);
    %         saveFigures(gca, fname2);
    %         fname3 = sprintf('SummaryFigureNonMod%s.png',kwargs.mname);
    %         saveFigures(gca, fname3);
    %     end

    %% rest


    %     statsData = allStats(sessionIdcs);
    %
    %     eventData = IkUtils.flatten({statsData.stats});%IkUtils.flatten({statsData.stats}, uniformOutput = true);
    %
    %     if isempty(eventData)
    %         peakTimes_ms = [];
    %         std_ms = [];
    %     else
    %         [peakTimes_ms, filterMask] = rejectSDOutliers([eventData.maxAmpTime] * 1000);
    %         std_ms = [eventData(filterMask).sd] * 1000;
    %     end
    %
    %     ymin = p.cspkRanges.(kwargs.event).min * 1000; %   0;
    %     ymax = p.cspkRanges.(kwargs.event).max * 1000; % 200;

    axs = [];
    figs = [];

    %     [axs, figs] = scatterWithBarCharts ...
    %         ( std_ms ...
    %         , peakTimes_ms ...
    %         , binwidth = 5 ...
    %         , xlim = [0 0.1]*1000 ...
    %         , ylim = [ymin ymax] ...
    %         , xlabel = "peak widths [ms]" ...
    %         , ylabel = "peak times [ms]" ...
    %         , title = sprintf ...
    %             ( "%s %s, %s %s" ...
    %             , mname ...
    %             , type ...
    %             , kwargs.event ...
    %             , ifelse(kwargs.modulating, "modulating", "non modulating") ...
    %             ) ...
    %         , subtitle = sprintf ...
    %             ( "N: %d, SD_y: %.2f, \\mu_x: %.2f" ...
    %             , numel(peakTimes_ms) ...
    %             , std(peakTimes_ms) ...
    %             , computeCspkTuningWidths ...
    %                 ( mname ...
    %                 , modulating = kwargs.modulating ...
    %                 , type = type ...
    %                 , event = kwargs.event ...
    %                 ).sds_mean ...
    %             ) ...
    %         );
    %
    %     axs(2).XTickLabel = {'0', '', '', '', '', '100'};
    %     axs(2).YTickLabel = {'0', '10', ''};

%   figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).cov] ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).cov] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).cov]; ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).cov] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('CV')
%     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('CV spk times CS fac MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotCVcsfacMUTvsWT.png'), 'png')
% 
%     figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).cov] ...
%         [allStatsWT.cs(cs_suppression_mask_WT).cov] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).cov]; ...
%         [allStatsWT.cs(cs_suppression_mask_WT).cov] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('CV')
%     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('CV spk times CS sup MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotCVcssupMUTvsWT.png'), 'png')
% figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).meanLcov] ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).meanLcov] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).meanLcov]; ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).meanLcov] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('LCV')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('LCV spk times CS fac MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotLCVcsfacMUTvsWT.png'), 'png')
% 
%     figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).meanLcov] ...
%         [allStatsWT.cs(cs_suppression_mask_WT).meanLcov] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).meanLcov]; ...
%         [allStatsWT.cs(cs_suppression_mask_WT).meanLcov] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('LCV')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('LCV spk times CS sup MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotLCVcssupMUTvsWT.png'), 'png')
%  figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).meanISIcs] ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).meanISIcs] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).meanISIcs]; ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).meanISIcs] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('ISI')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('ISI spk times CS fac MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotISIcsfacMUTvsWT.png'), 'png')
% 
%     figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).meanISIcs] ...
%         [allStatsWT.cs(cs_suppression_mask_WT).meanISIcs] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).meanISIcs]; ...
%         [allStatsWT.cs(cs_suppression_mask_WT).meanISIcs] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('ISI')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('ISI spk times CS sup MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotISIcssupMUTvsWT.png'), 'png')
%  figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).rate] ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).rate] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).rate]; ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).rate] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('freq')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('freq spk times CS fac MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotfreqcsfacMUTvsWT.png'), 'png')
% 
%     figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).rate] ...
%         [allStatsWT.cs(cs_suppression_mask_WT).rate] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).rate]; ...
%         [allStatsWT.cs(cs_suppression_mask_WT).rate] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('freq')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('freq spk times CS sup MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotfreqcssupMUTvsWT.png'), 'png')
% figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).maxAmpTime] ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).maxAmpTime] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).maxAmpTime]; ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).maxAmpTime] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('PT')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('PT spk times CS fac MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotPTcsfacMUTvsWT.png'), 'png')
% 
%     figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).maxAmpTime] ...
%         [allStatsWT.cs(cs_suppression_mask_WT).maxAmpTime] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).maxAmpTime]; ...
%         [allStatsWT.cs(cs_suppression_mask_WT).maxAmpTime] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('PT')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('PT spk times CS sup MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotPTcssupMUTvsWT.png'), 'png')
% figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).sd] ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).sd] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_facilitation_mask_MUT).sd]; ...
%         [allStatsWT.cs(cs_facilitation_mask_WT).sd] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('sd')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('sd spk times CS fac MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotsdcsfacMUTvsWT.png'), 'png')
% 
%     figure()
%     boxplot_data = [ ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).sd] ...
%         [allStatsWT.cs(cs_suppression_mask_WT).sd] ...
%         ];
%     boxplot_data_cell = { ...
%         [allStatsMUT.cs(cs_suppression_mask_MUT).sd]; ...
%         [allStatsWT.cs(cs_suppression_mask_WT).sd] ...        
%         };
%     grp = cell2mat(arrayfun(@(i){i*ones(numel(boxplot_data_cell{i}),1)},(1:numel(boxplot_data_cell))'));
%     boxplot_labels = {'MUT','WT'};
%     boxplot_labels_new = {boxplot_labels{unique(grp)}};
%     boxplot(boxplot_data, grp, 'labels', boxplot_labels_new, 'orientation','horizontal')
%     ylabel('Genotype')
%     xlabel('sd')
% %     xlim([0.002 0.004]);
%     set(gca,'tickdir','out','box','off');
%     title(sprintf('sd spk times CS sup MUT vs WT'))
% 
%     saveas(gcf, sprintf('/home/i.klinkhamer/Documents/Figures/SummaryFigures/boxplotsdcssupMUTvsWT.png'), 'png')

end