function saveSimpleMasks(mname, masks)
    
%     filePath = fullfile ... % IK change
%         ( cspkResultsFolder() ...
%         , sprintf ...
%             ( "simpleChannelMasks_%s_%d.mat" ...
%             , mname ...
%             , IkUtils.now ...
%             ) ...
%         );

path_ = IkUtils.getFilePath(mname);
filePath = fullfile(path_(1), sprintf("simpleChannelMasks_%s_%s.mat", mname,IkUtils.Now)); % IK change

save(filePath, "masks")

end