function viewDataSessionWrapper(axs, sessionData, channelMask, sessionIdx, mname)

p = IkUtils.getParams();

cspkRanges = p.sspkRanges;

channels = find(channelMask);
%channels = [1, 2, 3]; % IK change
for i = 1:numel(channels)
    c = channels(i);

    histStats = struct ...
        ( cs = computePsthStats ...
        ( sessionData.neuron(c).RasterXY_cs ...
        , cspkRanges.cs ...
        , p.psthRanges.cs_full ...
        ) ... % IK removed prior
        , us = computePsthStats ...
        ( sessionData.neuron(c).RasterXY_us ...
        , cspkRanges.us ...
        , p.psthRanges.us_full ...
        ) ...
        );
    try % IK TODO: fix this
        viewChannelSpikes ...
            ( axs ...
            , sessionData.neuron(c) ...
            , sessionData.irc_trueID(c) ...% IK change
            , sessionIdx ...
            , mname ...
            , histStats ...
            , trialTypes = [] ... % IK change
            );
    catch
        try
            viewChannelSpikes ...
                ( axs ...
                , sessionData.neuron(c) ...
                , sessionData.irc_trueID_all_neurons(c) ...% IK change
                , sessionIdx ...
                , mname ...
                , histStats ...
                , trialTypes = [] ... % IK change
                );
        catch
            idx = nan;
            viewChannelSpikes ...
                ( axs ...
                , sessionData.neuron(c) ...
                , idx ...% IK change
                , sessionIdx ...
                , mname ...
                , histStats ...
                , trialTypes = [] ... % IK change
                );
        end
    end

    if IkUtils.do_prompt_yes_or_no("Save to disk?") % IK change
        set(0, 'defaultFigureRenderer', 'painters');
        fig = axs(1).Parent;
        cacheUnits = fig.Units;
        cachePos = fig.Position;
        fig.Units = 'pixels';
        %fig.Position([3 4]) = [900 750];
        %             folder = fullfile ...
        %                 ( Env.getBayesLabUserRoot() ...
        %                 , "TraceExperiments" ...
        %                 , "ComplexSpikeToolkit" ...
        %                 , "CSpk_Suite_revised" ...
        %                 , "paperFigures" ...
        %                 );

        %         folder = IkUtils.getFilePath(mname); % IK change
        folder = "/home/i.klinkhamer/Documents/Figures/curation/new/";


        try
            file = sprintf ...
                ( "exemplary_%s_S=%d_N=%d.eps" ...
                , mname ...
                , sessionIdx ...
                , sessionData.irc_trueID_all_neurons(c) ... % IK change
                );
        catch
            try
                file = sprintf ...
                    ( "exemplary_%s_S=%d_N=%d.eps" ...
                    , mname ...
                    , sessionIdx ...
                    , sessionData.irc_trueID(c) ... % IK change
                    );
            catch
                file = sprintf ...
                    ( "exemplary_%s_S=%d_N=%s.eps" ...
                    , mname ...
                    , sessionIdx ...
                    , IkUtils.Now() ... % IK change
                    );
            end
        end

        print(fig, '-depsc', '-painters', fullfile(folder, file))

        try
            file = sprintf ...
                ( "exemplary_%s_S=%d_N=%d.jpg" ...
                , mname ...
                , sessionIdx ...
                , sessionData.irc_trueID_all_neurons(c) ... % IK change
                );
        catch
            try
                file = sprintf ...
                    ( "exemplary_%s_S=%d_N=%d.jpg" ...
                    , mname ...
                    , sessionIdx ...
                    , sessionData.irc_trueID(c) ... % IK change
                    );
            catch
                file = sprintf ...
                    ( "exemplary_%s_S=%d_N=%s.jpg" ...
                    , mname ...
                    , sessionIdx ...
                    , IkUtils.Now() ... % IK change
                    );
            end
        end

        print(fig, '-djpeg', '-painters', fullfile(folder, file))

        fig.Units = cacheUnits;
        fig.Position = cachePos;
    end

end

end