%% IK 2-11-23
function main()
arguments
end

%IkUtils.addPaths(mfilename);

choiceMap = ...
    { "Change path in prm file"             , @setCorrectProbePath...
    ; "Make folders"                        , @IkUtils.makeFolders...
    ; "Save spikes for cebra all sessions"  , @saveSpikeTimesAllNeurons...
    ; "Eyelid traces single sessions"       , @batchProcessTrialsExampleIK...
    ; "Eyelid traces overview"              , @overviewTraces...
    ; "EphysOverview"                       , @ephysOverview...    
    ; "View examplary neurons"              , @viewExemplaryChannelsMouseWrapper...
    ; "Spike sorting"                       , @initSpikeSorting...
    ; "Convert raw ephys data"              , @convertData...
    ; "Make unit from irc output"           , @unitConstruction...
    ; "Curate simple spikes"                , @simpleCurationMouseWrapper...
    ; "Debug"                               , @keyboard ...
    ; "Quit"                                , @() disp("Exiting ...") ...
    };

choices = [choiceMap{:,1}];

choice = "";

while ~strcmp(choice, "Quit")
    fprintf("\n-----------------------")
    fprintf("\nWhat do you want to do?")
    fprintf("\n-----------------------\n")

    [choice, choice_idx] = IkUtils.do_prompt_select_option(choices);

    choiceMap{choice_idx,2}()

end
end